// LOCALHOST 
### 
GET http://localhost:8080/poke-data

###
GET http://localhost:8080/poke-data

### 
GET http://localhost:8080/poke-data/63ba2c1898a0c4386448e05f

### 
GET http://localhost:8080/poke-data/63ba2c1898a0c4386448e06a

// PRODUCTION Deploy 
### 
GET https://week07.onrender.com/poke-data HTTP/1.1 content-type: application/json

### 
GET https://week07.onrender.com/poke-data HTTP/1.1 content-type: application/json

### 
GET https://week07.onrender.com/poke-data/63ba2c1898a0c4386448e05e HTTP/1.1 content-type: application/json

### 
GET https://week07.onrender.com/poke-data/63ba2c1898a0c4386448e06b HTTP/1.1 content-type: application/json

###
POST http://localhost:8080/poke-data/
content-type: application/json

{
    "name":"Squirtle",
    "number":"7",
    "type":["Water"],
    "image":"https://img.pokemondb.net/artwork/vector/large/squirtle.png",
    "shiny":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/7.png",
    "height":"0.5 m (1′08″)",
    "weight":"9.0 kg (19.8 lbs)"
}

###
POST http://localhost:8080/poke-data/
content-type: application/json

{
    "name":"Pauruga",
    "number":"968574",
    "badges":["Ice, Normal, Flying"],
    "height":"1.7 m (5′07″)",
    "weight":"71.7 kg (158 lbs)"
}


###
POST https://week07.onrender.com/poke-data
content-type: application/json

{
    "name":"Wartortle",
    "number":8,
    "type":["Water"],
    "image":"https://img.pokemondb.net/artwork/vector/large/wartortle.png",
    "shiny":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/8.png",
    "height":"1.0 m (3′03″)",
    "weight":"22.5 kg (49.6 lbs)"
}

###
POST https://week07.onrender.com/poke-data
content-type: application/json

{
    "name":"Stersh",
    "number":"142536",
    "badges":["Grass, Fire, Ghost"],
    "height":"1.8 m (5′11″)",
    "weight":"95.3 kg (210 lbs)"
}

###
PUT http://localhost:8080/poke-data/63ba2c1898a0c4386448e05a
content-type: application/json

{
    "name":"Bulbasaur",
    "number":"1",
    "type":["Grass", "Poison"],
    "image":"https://img.pokemondb.net/artwork/large/bulbasaur.jpg",
    "shiny":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/1.png",
    "height":"0.7 m (2′04″)",
    "weight":"6.9 kg (15.2 lbs)"
}

###
PUT http://localhost:8080/poke-data/63ba2c1898a0c4386448e06d
content-type: application/json

{
    "name":"Mr. Prez",
    "number":"748596",
    "badges":["Rock","Ghost", "Dark", "Steel"],
    "height":"1.6 m (5′4″)",
    "weight":"95.3 kg (210 lbs)"
}

###
PUT https://week07.onrender.com/poke-data/63ba2c1898a0c4386448e05d
content-type: application/json

{
    "name":"Charmander",
    "number":"4",
    "type":["Fire"],
    "image":"https://img.pokemondb.net/artwork/large/charmander.jpg",
    "shiny":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/4.png",
    "height":"0.6 m (2′00″)",
    "weight":"8.5 kg (18.7 lbs)"
}

###
PUT https://week07.onrender.com/poke-data/63ba2c1898a0c4386448e06c
content-type: application/json

{
    "name":"RazzyJay",
    "number":"102365",
    "badges":["Fairy","Ground", "Grass", "Electric"],
    "height":"1.7 m (5′5″)",
    "weight":"68.0 kg (150 lbs)"
}

###
 DELETE http://localhost:8080/poke-data/

 ###
 DELETE http://localhost:8080/poke-data/

###
 DELETE https://week07.onrender.com/poke-data/

 ###
 DELETE https://week07.onrender.com/poke-data/